package block

import "testing"

func TestSplitAndClassify(t *testing.T) {
	body := "Intro prose here.\n\n\tcode block\n\n  - a list\n  - item two\n\n# Heading\n\n[ref]: https://example.com\n\nMore prose."
	blocks := Split(body)
	want := []Kind{Prose, Verbatim, Verbatim, Verbatim, Verbatim, Prose}
	if len(blocks) != len(want) {
		t.Fatalf("got %d blocks, want %d: %+v", len(blocks), len(want), blocks)
	}
	for i, k := range want {
		if blocks[i].Kind != k {
			t.Errorf("block %d kind = %v, want %v (lines %q)", i, blocks[i].Kind, k, blocks[i].Lines)
		}
	}
}

func TestClassifyMixedBlockIsVerbatim(t *testing.T) {
	// A prose lead-in followed by indented list lines (no blank between) must be
	// preserved verbatim so the indented lines are not folded.
	body := "Options:\n  - first\n  - second"
	blocks := Split(body)
	if len(blocks) != 1 {
		t.Fatalf("got %d blocks, want 1", len(blocks))
	}
	if blocks[0].Kind != Verbatim {
		t.Errorf("mixed prose+indented block: kind = %v, want Verbatim", blocks[0].Kind)
	}
}

func TestFoldable(t *testing.T) {
	tests := []struct {
		line string
		want bool
	}{
		{"plain prose line", true},
		{"  indented", false},
		{"\tindented", false},
		{"- bullet", false},
		{"1. numbered", false},
		{"# heading", false},
		{"## subheading", false},
		{"### deep heading", false},
		{"[spec]: https://example.com", false},
		{"[not a def] but prose", true},
	}
	for _, tc := range tests {
		if got := foldable(tc.line); got != tc.want {
			t.Errorf("foldable(%q) = %v, want %v", tc.line, got, tc.want)
		}
	}
}

func TestSplitCollapsesBlankRuns(t *testing.T) {
	blocks := Split("\n\na\n\n\n\nb\n\n")
	if len(blocks) != 2 {
		t.Fatalf("got %d blocks, want 2", len(blocks))
	}
}

func TestIsDirective(t *testing.T) {
	tests := []struct {
		raw  string
		want bool
	}{
		{"//go:generate stringer", true},
		{"//go:build linux", true},
		{"//go:noinline", true},
		{"//nolint:all", true},
		{"//nolint", true},
		{"//revive:disable", true},
		{"// SPDX-License-Identifier: MIT", true},
		{"// SPDX-FileCopyrightText: 2026 Fred", true},
		{"//line foo.go:1", true},
		{"// +build linux", true},
		{"// a normal comment", false},
		{"// go: with a space is prose", false},
	}
	for _, tc := range tests {
		if got := IsDirective(tc.raw); got != tc.want {
			t.Errorf("IsDirective(%q) = %v, want %v", tc.raw, got, tc.want)
		}
	}
}

func TestIsExampleOutput(t *testing.T) {
	tests := []struct {
		raw  string
		want bool
	}{
		{"// Output:", true},
		{"// Output: single line", true},
		{"//Output:", true},
		{"// output:", true},
		{"// Unordered output:", true},
		{"// unordered output:", true},
		{"// Output:\n// hello\n// world", true},
		{"//   Output:", true}, // extra space after the marker
		{"// Outputs are great", false},
		{"// Note the output: here", false},
		{"// a normal comment", false},
	}
	for _, tc := range tests {
		if got := IsExampleOutput(tc.raw); got != tc.want {
			t.Errorf("IsExampleOutput(%q) = %v, want %v", tc.raw, got, tc.want)
		}
	}
}

func TestIsGenerated(t *testing.T) {
	gen := []byte("// Code generated by tool. DO NOT EDIT.\n\npackage p\n")
	if !IsGenerated(gen) {
		t.Error("expected generated file to be detected")
	}
	notGen := []byte("// Code generated by hand.\n\npackage p\n")
	if IsGenerated(notGen) {
		t.Error("did not expect detection without DO NOT EDIT marker")
	}
	after := []byte("package p\n\n// Code generated x. DO NOT EDIT.\n")
	if IsGenerated(after) {
		t.Error("marker after package clause must not count")
	}
}
