package block

import "testing"

func TestSplitAndClassify(t *testing.T) {
	body := "Intro prose here.\n\n\tcode block\n\n  - a list\n  - item two\n\n# Heading\n\nMore prose."
	blocks := Split(body)
	want := []Kind{Prose, Code, List, Heading, Prose}
	if len(blocks) != len(want) {
		t.Fatalf("got %d blocks, want %d: %+v", len(blocks), len(want), blocks)
	}
	for i, k := range want {
		if blocks[i].Kind != k {
			t.Errorf("block %d kind = %v, want %v (lines %q)", i, blocks[i].Kind, k, blocks[i].Lines)
		}
	}
}

func TestSplitCollapsesBlankRuns(t *testing.T) {
	blocks := Split("\n\na\n\n\n\nb\n\n")
	if len(blocks) != 2 {
		t.Fatalf("got %d blocks, want 2", len(blocks))
	}
}

func TestIsDirective(t *testing.T) {
	tests := []struct {
		raw  string
		want bool
	}{
		{"//go:generate stringer", true},
		{"//go:build linux", true},
		{"//nolint:all", true},
		{"//revive:disable", true},
		{"//line foo.go:1", true},
		{"// +build linux", true},
		{"// a normal comment", false},
		{"// go: with a space is prose", false},
	}
	for _, tc := range tests {
		if got := IsDirective(tc.raw); got != tc.want {
			t.Errorf("IsDirective(%q) = %v, want %v", tc.raw, got, tc.want)
		}
	}
}

func TestIsGenerated(t *testing.T) {
	gen := []byte("// Code generated by tool. DO NOT EDIT.\n\npackage p\n")
	if !IsGenerated(gen) {
		t.Error("expected generated file to be detected")
	}
	notGen := []byte("// Code generated by hand.\n\npackage p\n")
	if IsGenerated(notGen) {
		t.Error("did not expect detection without DO NOT EDIT marker")
	}
	after := []byte("package p\n\n// Code generated x. DO NOT EDIT.\n")
	if IsGenerated(after) {
		t.Error("marker after package clause must not count")
	}
}
